Traceback (most recent call last):
  File "C:\anaconda\envs\jbook\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\anaconda\envs\jbook\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np

df = pd.read_csv('./data/1_dbs_data.csv', delimiter=';', header=[2,3], encoding='ISO-8859-1', low_memory=False)

sum_row = df.loc[(df[('NR','Unnamed: 0_level_1')] == 'Summe')]

library_df = sum_row.astype('string')

for label, content in library_df.iteritems():
    library_df[label] = library_df[label].str.replace('.', '', regex=True)
    library_df[label] = library_df[label].str.replace(',', '.', regex=True)

library_df = pd.melt(library_df)
library_df = library_df.rename(columns={"variable_0": "Auspraegung", 'variable_1': 'Jahr', 'value': 'Wert'})

library_df = library_df.drop([0, 1, 2, 3, 103])

library_df = library_df.pivot(index='Jahr', columns='Auspraegung', values='Wert')

for label, content in library_df.iteritems():
    library_df[label] = library_df[label].astype(float)

library_df.reset_index(inplace=True)

pop_df = pd.read_csv('./data/1_pop_data.csv', delimiter=';', header=[5])

pop_df = pop_df.drop([11, 12, 13, 14])

pop_df = pop_df.rename(columns={"Unnamed: 0": "Jahr"})

pop_df['Anzahl'] = pop_df['Anzahl'].astype(int)

pop_df['Jahr'] = pd.to_datetime(pop_df['Jahr'], format='%d.%m.%Y')

df = pd.DataFrame(
    {
        # general info
        'year' : ([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]),
        'population' : pop_df['Anzahl'],
        
        # reading habits
        'digital_readers': ([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 7650000, 8520000, 8680000, 9120000]),

        'readers_weekly' : ([20400000, 20500000, 20000000, 19300000, 18500000, 18100000, 18100000, 11640000, 11930000, 11960000, 12620000]),
        'readers_monthly' : ([20900000, 20500000, 20600000, 21100000, 21300000, 20200000, 20100000, 15070000, 14840000, 14730000, 14710000]),
        'readers_once_month' : ([12000000, 11500000, 10100000, 10000000, 10400000, 10400000, 10100000, 6870000, 7060000, 7110000, 7030000]),

        # publishing information
        'ebook_sales': ([1900000, 4300000, 13200000, 21500000, 24800000, 27000000, 28100000, 29100000, 32800000, 32400000, 35800000]),

        # library information
        'lenders': library_df['Entleiher'],
        'lendings': library_df['Entleih. insges.'],
        'digital_lendings': library_df['Entl. virt.Best.'], 
        
    }
)

df['readers'] = df['readers_weekly'] + df['readers_monthly'] + df['readers_once_month']

# readers relative to the population over the years
df['perc_digital_readers'] = df['digital_readers'] / df['population']
df['perc_readers'] = df['readers'] / df['population']
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUnicodeDecodeError[0m                        Traceback (most recent call last)
[1;32mC:\Users\VERENA~1\AppData\Local\Temp/ipykernel_17580/3006520070.py[0m in [0;36m<module>[1;34m[0m
[0;32m     24[0m [0mlibrary_df[0m[1;33m.[0m[0mreset_index[0m[1;33m([0m[0minplace[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     25[0m [1;33m[0m[0m
[1;32m---> 26[1;33m [0mpop_df[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'./data/1_pop_data.csv'[0m[1;33m,[0m [0mdelimiter[0m[1;33m=[0m[1;34m';'[0m[1;33m,[0m [0mheader[0m[1;33m=[0m[1;33m[[0m[1;36m5[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     27[0m [1;33m[0m[0m
[0;32m     28[0m [0mpop_df[0m [1;33m=[0m [0mpop_df[0m[1;33m.[0m[0mdrop[0m[1;33m([0m[1;33m[[0m[1;36m11[0m[1;33m,[0m [1;36m12[0m[1;33m,[0m [1;36m13[0m[1;33m,[0m [1;36m14[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    309[0m                     [0mstacklevel[0m[1;33m=[0m[0mstacklevel[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    310[0m                 )
[1;32m--> 311[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    312[0m [1;33m[0m[0m
[0;32m    313[0m         [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[0;32m    584[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    585[0m [1;33m[0m[0m
[1;32m--> 586[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    587[0m [1;33m[0m[0m
[0;32m    588[0m [1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    480[0m [1;33m[0m[0m
[0;32m    481[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 482[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    483[0m [1;33m[0m[0m
[0;32m    484[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m    809[0m             [0mself[0m[1;33m.[0m[0moptions[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m [1;33m=[0m [0mkwds[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    810[0m [1;33m[0m[0m
[1;32m--> 811[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    812[0m [1;33m[0m[0m
[0;32m    813[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_make_engine[1;34m(self, engine)[0m
[0;32m   1038[0m             )
[0;32m   1039[0m         [1;31m# error: Too many arguments for "ParserBase"[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1040[1;33m         [1;32mreturn[0m [0mmapping[0m[1;33m[[0m[0mengine[0m[1;33m][0m[1;33m([0m[0mself[0m[1;33m.[0m[0mf[0m[1;33m,[0m [1;33m**[0m[0mself[0m[1;33m.[0m[0moptions[0m[1;33m)[0m  [1;31m# type: ignore[call-arg][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1041[0m [1;33m[0m[0m
[0;32m   1042[0m     [1;32mdef[0m [0m_failover_to_python[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py[0m in [0;36m__init__[1;34m(self, src, **kwds)[0m
[0;32m     67[0m         [0mkwds[0m[1;33m[[0m[1;34m"dtype"[0m[1;33m][0m [1;33m=[0m [0mensure_dtype_objs[0m[1;33m([0m[0mkwds[0m[1;33m.[0m[0mget[0m[1;33m([0m[1;34m"dtype"[0m[1;33m,[0m [1;32mNone[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     68[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 69[1;33m             [0mself[0m[1;33m.[0m[0m_reader[0m [1;33m=[0m [0mparsers[0m[1;33m.[0m[0mTextReader[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mhandles[0m[1;33m.[0m[0mhandle[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     70[0m         [1;32mexcept[0m [0mException[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     71[0m             [0mself[0m[1;33m.[0m[0mhandles[0m[1;33m.[0m[0mclose[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader.__cinit__[1;34m()[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader._get_header[1;34m()[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader._tokenize_rows[1;34m()[0m

[1;32mC:\anaconda\envs\jbook\lib\site-packages\pandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.raise_parser_error[1;34m()[0m

[1;31mUnicodeDecodeError[0m: 'utf-8' codec can't decode byte 0xf6 in position 31: invalid start byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 31: invalid start byte

